on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        working-directory: side_bar_animation/side_bar_animation
        run: flutter pub get

      - name: Build APK (Android)
        working-directory: side_bar_animation/side_bar_animation
        run: flutter build apk --release --split-per-abi

      - name: Build iOS (IPA)
        if: runner.os == 'macOS'  # iOS build only works on macOS
        working-directory: side_bar_animation/side_bar_animation
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            side_bar_animation/side_bar_animation/build/app/outputs/apk/release/*.apk
            side_bar_animation/side_bar_animation/build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
